### ISSUE TITLE
"go get cmd" fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by bretton** [michael1011/lightningtip#1]
Install docs say
```
go get github.com/michael1011/lightningtip.git
```
but this gives the following error:
```
package github.com/michael1011/lightningtip.git: invalid version control suffix in github.com/ path
```

Seems to work with the following as the first step, will see shortly
```
git clone https://github.com/michael1011/lightningtip.git $GOPATH/src/github.com/michael1011/lightningtip.git
```

**Comment by bretton** [comment]
This seems work more like I'd expect it to

```
git clone https://github.com/michael1011/lightningtip.git $GOPATH/src/github.com/michael1011/lightningtip
cd $GOPATH/src/github.com/michael1011/lightningtip
dep ensure
go install
```

this then creates the binary `~/go/bin/lightningtip`

Missing information:
- running lightningtip, does it have to run all the time? How (can setup via supervisord)

And it's not clear from "The default config file location is lightningTip.conf in the directory you are executing LightningTip in." whether this means `~/go/bin/` or the web server root?

**Comment by bretton** [comment]
I created $HOME/.lightningtip

I added $HOME/.lightningtip/lightningtip.conf

I started lightningtip with
```
lightningtip --config=/home/username/.lightningtip/lightningTip.conf
```
I also had to specify 
```
resthost = <mypublicIP>:8081
```
and now see the following on startup
```
2018-03-29 22:12:01.014 [DEBUG] Successfully initialized log file
2018-03-29 22:12:01.016 [INFO] Starting EventSource stream
2018-03-29 22:12:01.016 [DEBUG] Starting ticker to clear expired invoices
2018-03-29 22:12:01.016 [INFO] Subscribing to invoices
2018-03-29 22:12:01.016 [INFO] Starting HTTP server
```

so that it would bind to a port
```
tcp        0      0 <myIP>:8081      0.0.0.0:*               LISTEN      10320/lightningtip
```

But still no success, front-end fails to connect.

**Comment by michael1011** [comment]
> running lightningtip, does it have to run all the time? How (can setup via supervisord)

Running LightningTip with systemd or supervisord is quite tricky. Because it has to start after LND was unlocked. Even after it is unlocked LND needs a few seconds to start the gRPC interface LightningTip is using.

**Comment by michael1011** [comment]
Yes systemd is able to start the LightningTip after LND. But the LND service does not unlock LND nor does it wait for LND to start the gRPC interface.

Would it be a good idea to restart LightningTip every 60 seconds until it is working? I am thinking of something like this:
```
Restart=on-failure
RestartSec=60
```

**Comment by bretton** [comment]
Yeah that's worth trying, will give it a go too.

**Comment by michael1011** [comment]
Created a [wiki page for running LightningTip with systemd](https://github.com/michael1011/lightningtip/wiki/Running-LightningTip-with-systemd) and linked it in the readme.

Could you do something similar for supervisord? I am not too familiar with it.

**Comment by bretton** [comment]
I'm not sure how to add wiki pages in git yet, quickest is to dump this here.

### Assumptions:

supervisor is installed

### Enable the lightningtip service via supervisor

Add a conf file for lightningtip to `supervisor` as follows:
```
cd /etc/supervisor/conf.d/
sudo nano lightningtip.conf
```

Add the following content:
```
[program:lightningtip]
user=REPLACE-LNTIP-USER
command=/home/REPLACE-LNTIP-USER/go/bin/lightningtip --config=/home/REPLACE-LNTIP-USER/.lightningtip/lightningTip.conf
startretries=999999999999999999999999999
autostart=true
autorestart=true
```

Then reload supervisor:
```
sudo supervisorctl reload
```
To stop run:
```
sudo supervisorctl stop lightningtip
```

To start again run:
```
sudo supervisorctl start lightningtip
```

**Comment by michael1011** [comment]
I mean a wiki page here on GitHub. For this repo [here](https://github.com/michael1011/lightningtip/wiki/_new).

**Comment by bretton** [comment]
"You do not have permission to update this wiki."

**Comment by michael1011** [comment]
Sorry. I didn't know that permissions are required to edit the wiki.

You should have gotten an invite. If you accept it you have the required permissions for editing.

**Comment by bretton** [comment]
Can probably close this issue now?

**Comment by michael1011** [comment]
Yes. Thank you very much 😄
