### ISSUE TITLE
mail.sender is only honoured if smtp server is set

### ISSUE THREAD

**Issue by bretton** [michael1011/lightningtip#11]
### Background

configuring the account notices get sent from only works when using a configured mail server, it doesn't work when using /usr/bin/mail 

This is not necessarily a bug or issue, just being noted for future support queries

### Your environment

* ubuntu 16.04 LTS
* are you running LightningTip behind a reverse proxy? No

### Steps to reproduce

If you configure lightningtip.conf with the following on a Linux system
```
[Mail]
mail.email = mail@send.to
# mail.server = 
mail.sender = lightningtup@account.from
mail.ssl = false
# mail.user =
# mail.password =
```
Then it will use /usr/bin/mail from the `mailutils` or `mailx` package.

### Expected behaviour

The sender account should be the configured email in the flag
```
mail.sender = lightningtup@account.from
```

### Actual behaviour

The sender is the user account `lightningtip` is being run under and NOT the configured sender in lightningtip.conf

### Important

This might be specific to /usr/bin/mail and NOT a bug. Just something to be noted.

If you wish to ensure the sending account is the one configured in lightningtip.conf just make sure you use a configured mail server, with your lightningtip.conf looking like the following

```
[Mail]
mail.email = mail@send.to
mail.server = hostname:port
mail.sender = lightningtup@account.from
mail.ssl = false
mail.user = mailuser@hostname
mail.password = userpassword
```

**Comment by michael1011** [comment]
Should be fixed now. In addition I changed the `mail.email` to `mail.recipient`

**Comment by bretton** [comment]
Awesome, works perfectly :)
