### ISSUE TITLE
Update macaroon path for 0.5 release of LND

### ISSUE THREAD

**Issue by bretton** [michael1011/lightningtip#12]
LND 0.5 changes the macaroon path. The new default macaroon path is 

```
$lnddir/data/chain/bitcoin/mainnet
```

or on linux
```
.lnd/data/chain/bitcoin/mainnet/invoice.macaroon
```
Adding as an issue because 0.5 isn't yet released, but very soon. 

Need to update LightingTip sample-lightningTip.conf, and not sure what else?

If a different default path for macroons is used, this needs to be specified in LND startup, and in any 3rd party tools.

**Comment by michael1011** [comment]
Thank you for bringing this up! I will probably release LightningTip version 1.1.0 that works with LND 0.5 out of the box. Nobody should stay on an old version of LND imo. When is 0.5 scheduled to be released? @bretton 

Also the default values in the config parser will have to be updated.

**Comment by michael1011** [comment]
Closed by [this commit](https://github.com/michael1011/lightningtip/commit/eefc315f4d13c994ec837d3368f5d3e77d989386)

**Comment by bretton** [comment]
awesome, thanks and well done 💯 
initial tests confirm all working provided macaroon path is set.

**Comment by michael1011** [comment]
Actually it should find the macaroon itself :thinking: 

Could you try not setting it in the config and just starting LightningTip? @bretton

**Comment by bretton** [comment]
You are correct, it works fine without specifically setting it. 

I had the old path set previously and updated to the new path.

**Comment by bretton** [comment]
Ahah, it has to be specifically set for my litecoind+lnd node, but works fine without setting on bitcoind+lnd
