### ISSUE TITLE
unable to reach backend

### ISSUE THREAD

**Issue by seth586** [michael1011/lightningtip#16]
### Background

Click 'get request' = 'Failed to reach backend'

### Your environment

FreeBSD 11.2
* lightningtip & jekyll webserver on same localhost
* lnd lnd v0.6-beta-rc4 on same local network 
* are you running LightningTip behind a reverse proxy? No.

### Steps to reproduce

lnd.conf:
```
[Application Options]
lnddir=/var/db/lnd
nat=true
restlisten=0.0.0.0:8080
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.dir=/var/db/bitcoin
```

lightningTip.conf:
```
[Application Options]
datadir = /var/db/lndtip
logfile = /var/db/lndtip/lightningTip.log
loglevel = debug
databasefile = /var/db/lndtip/tips.db
resthost = localhost:8081
accessdomain = *
tipexpiry = 3600
reconnectinterval = 5

[LND]
lnd.grpchost = 192.168.84.208:10009
lnd.certfile = /var/db/lndtip/tls.cert
lnd.macaroonfile = /var/db/lndtip/invoice.macaroon
```

lightningTip.log:
```
2019-04-16 16:08:18 [DEBUG] Parsed config file: /var/db/lndtip/lndtip.conf
2019-04-16 16:08:18 [DEBUG] Initialized log file: /var/db/lndtip/lightningTip.log
2019-04-16 16:08:18 [DEBUG] Opened SQLite database: /var/db/lndtip/tips.db
2019-04-16 16:08:18 [INFO] Starting EventSource stream
2019-04-16 16:08:18 [DEBUG] Starting ticker to clear expired invoices
2019-04-16 16:08:18 [INFO] Starting HTTP server
2019-04-16 16:08:18 [INFO] Subscribing to invoices
```

lightningTip.js:
```
var requestUrl = "http://localhost:8081/";
...
```

**Comment by seth586** [comment]
Tried with a basic install of lighttpd as well, same message.

**Comment by michael1011** [comment]
The error is in the `lightningTip.js`:
```
var requestUrl = "http://localhost:8081/";
```

Replace `http://localhost:8081/` with whatever the URL or IP of your server is and try again

**Comment by seth586** [comment]
I replaced the following lines:
`Lightningtip.js:`
```
var requestUrl = "http://192.168.84.237:8081/";
```
Which did not in and of itself fix it, but also changing
`lightningTip.conf`:
```
resthost = 192.168.84.237:8081
```
Successfully worked! Not sure why, I would think that since lightningtip and the webserver are on the same machine, a `localhost` would work. 

Thank you!
