### ISSUE TITLE
lightningtip is running on port 8081 but gives error "not found"

### ISSUE THREAD

**Issue by bretton** [michael1011/lightningtip#3]
Still unable to load the web frontend, but I can access port 8081 while `lightingtip` is running. 

Unfortunately it says
```
{
    "Error": "Not found"
}
```

**Comment by BubbleCoinLOL** [comment]
Same here.

**Comment by bretton** [comment]
I've done that, but get the error "Failed to reach backend"

I tried accessing the 8081 port directly to see if any response, and got the issue above

**Comment by michael1011** [comment]
This is normal. Did you try changing the variable `requestUrl ` in the JavaScript file? If so: could you show me the output of the console in the browser?

**Comment by michael1011** [comment]
Just make sure the `requestUrl` in the first line of the JavaScript file is correct.

If you are using a proxy make sure it is configured to support [EventSource](https://developer.mozilla.org/de/docs/Web/API/EventSource) (Server side events). [Help for Nginx](https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate)

I want to apologize again for the issues you are having. If you manage to set it up I will tip you a few satoshis. Just send me the URL on [Twitter ](https://twitter.com/michael1011at) or via Email me@michael1011.at.

**Comment by bretton** [comment]
awesome thanks, will keep bashing away at it, and share useful documentation :)

**Comment by michael1011** [comment]
You are great! 😄

Thank you for testing my buggy software and feel to write me anytime.

**Comment by bretton** [comment]
The problem is my webserver is https, and the lightningtip rest service is not, so a garbled response results, which is interpreted as a failure to connect to backend. I got it working as follows:

in `$HOME/.lightningtip/lightningtip.conf`
```
resthost = localhost:10000
```

then setup a reverse proxy in nginx in `/etc/nginx/sites-available/default` as follows
```
server {
	listen 8081;
	listen [::]:8081;

	server_name YOUR_SERVER_NAME;

	ssl on;
	ssl_certificate /path/to/your/ssl/cert;
	ssl_certificate_key /path/to/your/ssl/key; 
	include /etc/letsencrypt/options-ssl-nginx.conf; # set by certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # set by certbot

	location / {
		proxy_http_version 1.1;
		proxy_pass http://127.0.0.1:10000;
		proxy_set_header Connection '';
		proxy_set_header Host $host;
		chunked_transfer_encoding off;
		proxy_buffering off;
		proxy_cache off;
       }
}
```

This will work with the default `lightningTip.js` without any changes in that file. 

The only changes are running `lightningtip` rest service on port 10000, and using nginx reverse proxy on port 8081 to that rest service.

**Comment by bretton** [comment]
I wonder if something along these lines would work, provided you're running `lightningtip` REST on port 10000, and configure Apache reverse proxy on port 8081
```
<VirtualHost *:8081>
    SSLEngine On
    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    SSLCertificateFile /etc/apache2/ssl/file.pem
    ProxyPreserveHost On
    ProxyPass / http://0.0.0.0:10000/
    ProxyPassReverse / http://0.0.0.0:10000/
    ServerName SERVERNAME
</VirtualHost>
```

**Comment by michael1011** [comment]
I will add the option to run LightningTip on HTTPS in the next commit.

**Comment by pieman64** [comment]
@michael1011 loving your work. Bit off topic but on the subject of commits what I think would be good is for the executable to be able to have a user variable input for "tip", "invoice" etc. This way businesses could set as "Payment for your meal", "Pay for your reservation", "Buy a coffee", "Send funds to a friend" etc. What do you think?

**Comment by michael1011** [comment]
Added this to the config:

```
# It is possible to use LightningTip over HTTPS instead of HTTP
# If you want to: edit "tlscertfile" and "tlskeyfile" accordingly
# tlscertfile =
# tlskeyfile =
```

Should work via HTTPS without the proxy now.

**Comment by michael1011** [comment]
@pieman64 It would be possible. But LightningTip was intended to handle tips. Maybe you could fork it for this use case?

**Comment by benvhool** [comment]
Thanks for the effort. Meanwhile I got it working by defining a proxy in apache2 as @bretton explained.

**Comment by bretton** [comment]
@benvhool did my apache config sample work as is, or was some additional info required? I can add a setup to the wiki for Apache too?

**Comment by benvhool** [comment]
Yes, I did get it to work. Thanks a lot.

2018-03-31 23:38 GMT+02:00 bretton <notifications@github.com>:

**Comment by bretton** [comment]
Ok cool, added https://github.com/michael1011/lightningtip/wiki/LightningTip-via-Apache2-reverse-proxy

I'm happy to close this issue.

**Comment by michael1011** [comment]
Thank you very much :smile: 

Should I add the new wiki entries to the README or do you want to do this?

**Comment by bretton** [comment]
I don't mind doing it, can get to it a little later today
