### ISSUE TITLE
cannot use con (type *"google.golang.org/grpc".ClientConn)

### ISSUE THREAD

**Issue by MSauce** [michael1011/lightningtip#6]
When attempting to 
`go get github.com/michael1011/lightningtip`

I'm getting:
github.com/michael1011/lightningtip/backends
gocode/src/github.com/michael1011/lightningtip/backends/lnd.go:54:39: cannot use con (type *"google.golang.org/grpc".ClientConn) as type *"github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc".ClientConn in argument to lnrpc.NewLightningClient

**Comment by michael1011** [comment]
Weird. I tried it with a clean Gopath on Windows 10 with Golang version 1.10 and it worked as it should.

Maybe the copies of LND or google.golang.org/grpc in you Gopath are outdated. Please try updating them with 
```
go get -u github.com/lightningnetwork/lnd
```

**Comment by MSauce** [comment]
Sorry should have been a bit more clear. Trying to build on Ubuntu 16.04, and LND was already updated to March 30th. I just pulled the last days updates just to check.

Same output:
gocode/src/github.com/michael1011/lightningtip/backends/lnd.go:54:39: cannot use con (type *"google.golang.org/grpc".ClientConn) as type *"github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc".ClientConn in argument to lnrpc.NewLightningClient

**Comment by michael1011** [comment]
I tried buliding it on my Raspberry Pi (Debian) and although it took a while it worked. 
Are you using Golang version 1.10? You can check this with `go version`.

**Comment by MSauce** [comment]
Yes - go version go1.10 linux/amd64 and go seems to be working fine with everything else. Weird...

**Comment by michael1011** [comment]
You could try cloning the repo into folder it belongs (`gocode/src/github.com/michael1011` in your case). [Installing dep](https://github.com/golang/dep), running `dep ensure` and then `go install`.

With this command you should have the exact same dependencies that I have.

**Comment by MSauce** [comment]
That seems to have worked fine (didn't return any output). A bit busy today but planning on playing around with this some in next few days! Thanks for your help

**Comment by michael1011** [comment]
Nice! I'm glad that I could help! 😄

**Comment by bretton** [comment]
Just noting that this works.

```
go get -d github.com/michael1011/lightningtip
```

**Comment by bretton** [comment]
```
usage: go get [-d] [-f] [-fix] [-insecure] [-t] [-u] [-v] [build flags] [packages]

Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.

The -d flag instructs get to stop after downloading the packages; that is,
it instructs get not to install the packages.

...

The -u flag instructs get to use the network to update the named packages
and their dependencies. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.
```

Looks like a decision between "-d" or "-u"?

**Comment by michael1011** [comment]
I would handle this issue the same way LND does.

For downloading the first time:
`go get -d github.com/lightningnetwork/lnd`

And for updating:
`cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull`

**Comment by bretton** [comment]
I've updated the readme, can probably re-close?

**Comment by michael1011** [comment]
Sure. Thank you! 😄
