### ISSUE TITLE
Missing QR code and countdown in latest commit

### ISSUE THREAD

**Issue by bretton** [michael1011/lightningtip#8]
The latest commit no longer shows the QR code, or countdown, in Chrome, Firefox and Safari.

`commit 15ad2efc4c788116c52441a9768f526b5256e992`

Display

![lightning invoice only](https://i.imgur.com/y9qh8QC.png)

I ran

```
cd $GOPATH/src/github.com/michael1011/lightningtip
git pull
dep ensure
go install
```

Then copied web files
```
cd frontend
cp lightningTip.css /path/to/webroot
cp lightningTip.js /path/to/webroot
```

And edited my index.html to replace
```
<textarea class="lightningTipInput" id="lightningTipMessage" placeholder="A message you want to add" oninput="resizeInput(this)"></textarea>
```

with

```
<div class="lightningTipInput" id="lightningTipMessage" placeholder="A message you want to add" oninput="divRestorePlaceholder(this)" onblur="divRestorePlaceholder(this)" contenteditable></div>
```

And now the QR code no longer shows, but invoice generation works fine. 

Just a display issue with the latest changes?

**Comment by bretton** [comment]
Fiddling around in Inspector doesn't seem to help much, such as changing size of the lightningTipQR div. There is no content and only the size can be edited with no change.

![inspectorview](https://i.imgur.com/L5uEBsv.jpg)

**Comment by michael1011** [comment]
Should be fixed in the [last commit](https://github.com/michael1011/lightningtip/commit/eaf91e5864aa8eca6e32a33837f2b0a1b9597c92). I forgot to remove a reference to a function which doesn't exist anymore.

**Comment by bretton** [comment]
Awesome, well done, that fixed it :)
