### ISSUE TITLE
"Not found" error always.

### ISSUE THREAD

**Issue by vegardengen** [michael1011/lightningtip#9]
I am running with node on a remote machine and an invoice.macaroon from that LND. As far as I can see, most things get initialized properly:

`2018-04-02` 10:45:50.506 [DEBUG] Parsed config file: /home/vegard/.lightningtip/lightningTip.conf
2018-04-02 10:45:50.506 [DEBUG] Initialized log file: /home/vegard/.lightningtip/lightningTip.log
2018-04-02 10:45:50.508 [INFO] Starting EventSource stream
2018-04-02 10:45:50.509 [DEBUG] Starting ticker to clear expired invoices
2018-04-02 10:45:50.509 [INFO] Subscribing to invoices
2018-04-02 10:45:50.510 [INFO] Starting HTTP server`

Pointing a web browser to it, I get:

`{
    "Error": "Not found"
}`

There is no clue in the log files as to what happens on my request, no logs from it...I run with debug loglevel.

**Comment by grunch** [comment]
the same here, there is no documentation about how it work

**Comment by michael1011** [comment]
Although the README says clearly that you should embed the HTML file I will add that you should not open the URL of the backend in your browser, change the error message to something like *"This is not meant to be opened in your browser"* and document the API of the backend

**Comment by fjcalderons** [comment]
it's good enough for me, great job by the way :+1:

**Comment by vegardengen** [comment]
Good enough for me too. Closing this issue :)
